[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_counter = "5UzK5Js2ZdAHSx34vCjhLG5TzPAfnpMRCuf2DJ6HLfdt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
